### ISSUE TITLE
Device is not registered in Tuya cloud

### ISSUE THREAD

**Issue by BRoadifer** [PlusPlus-ua/ha_tuya_ble#49]
I get Device is not registered in Tuya cloud when trying to configure devices/integrations.  I can see that they show as Tuya BLE. I also see that they show under Devices when I log into the Tuya IoT Platform Cloud.

**Comment by PlusPlus-ua** [comment]
Could you please provide logs, enable debug logging before collecting the log please. 

Use something like this in your configuration.yaml:

```
logger:
  default: info
  logs:
    custom_components.tuya_ble: debug

```
